title: OptimalCharB's Documentation
description: Documentation for OptimalCharB's projects
baseurl: "/optimalcharb.github.io"
url: "https://optimalcharb.github.io"

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable: true

theme: minima

