markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

title: Charlie Bauer
description: personal website

plugins:
- jekyll-remote-theme
remote_theme: pages-themes/slate@v0.2.0