markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

title: Charlie Bauer
description: personal website

plugins:
- jekyll-remote-theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"